#ifndef _PLAYER_H_
#define _PLAYER_H_

#define IS_KAIO(ch) (!str_cmp(get_race(ch), "kaio"))
#define IS_DEMON(ch) (!str_cmp(get_race(ch), "demon"))
#define IS_MUTANT(ch) (!str_cmp(get_race(ch), "mutant"))
#define IS_CANDYMAN(ch) (!str_cmp(get_race(ch), "candyman"))
#define IS_ARCHDEMON(ch) (!str_cmp(get_race(ch), "archdemon"))
#define IS_ARCHANGEL(ch) (!str_cmp(get_race(ch), "archangel"))
#define IS_NEPHALIM(ch) (!str_cmp(get_race(ch), "nephalim"))
#define IS_SAIBAMAN(ch) (!str_cmp(get_race(ch), "saibaman"))
#define IS_GENIE(ch) (!str_cmp(get_race(ch), "genie"))
#define SAIYANRANKED(character)  (is_saiyan(character) && character->rank > 0)
#define IS_KAIRANKED(ch) (IS_KAIO(ch) && ch->rank >0)
#define IS_DEMONRANKED(ch) (IS_DEMON(ch) && ch->rank > 0)
#define IS_FUSED(ch) (ch->fusions > 0)
#define IS_RANKED(ch) (ch->rank > 0)
#define IS_MAXXED(ch) (ch->exp > 200000000000000000ULL)
#define IS_MINUS_GAINS(ch) (weightedClothingPlMod( ch ) < 0)
#define IS_TOSHIRO(ch) (!str_cmp(ch->name, "Toshiro"))
#define IS_SCAPEGOAT(ch) (!str_cmp(ch->name, "Toka"))
#define IS_ICER(ch)  (!str_cmp(get_race(ch), "icer"))
#define IS_BIOANDROID(ch)  (ch->race == 6)
#define IS_REPLOID(ch)  (!str_cmp(get_race(ch), "reploid"))
#define IS_SIDEON(ch) (!str_cmp(ch->name, "Sideon"))
#define IS_ANNOYING(ch) (!str_cmp(ch->name, "Sebine"))
#define IS_ALTHAS(ch) (!str_cmp(ch->name, "Althasizor"))
#define IS_RANDY(ch) (!str_cmp(ch->name, "Subzero"))
#define IS_BLKMAGE(ch) (!str_cmp(ch->name, "Vivi"))
#define IS_ICHIGO(ch) (!str_cmp(ch->name, "Ichigo"))
#define IS_MATT(ch) (!str_cmp(ch->name, "Ketts"))
#define IS_BAAL(ch) (!str_cmp(ch->name, "Baal"))
#define IS_AKIO(ch) (!str_cmp(ch->name, "Akio"))
#define IS_KAL(ch) (!str_cmp(ch->name, "Kalthizar"))
#define IS_AUSTIN(ch) (!str_cmp(ch->name, "Kazuma"))
#define IS_IRONMAN(ch) (!str_cmp(ch->name, "Tony"))
#define IS_NICCI(ch) (!str_cmp(ch->name, "Kotoko"))
#define IS_MALIK(ch) (!str_cmp(ch->name, "Malik"))
#define IS_SHOMA(ch) (!str_cmp(ch->name, "Shoma"))
#define IS_KARRIE(ch) (!str_cmp(ch->name, "Orihime"))
#define IS_AIZEN(ch) (!str_cmp(ch->name, "Aizen"))
#define IS_NATALIA(ch) (!str_cmp(ch->name, "Natalia"))
#define IS_VIDEL(ch) (!str_cmp(ch->name, "Videl"))
#define IS_RINI(ch) (!str_cmp(ch->name, "Daralys"))
#define IS_RINI2(ch) (!str_cmp(ch->name, "Maracella"))
#define IS_SOPHIA(ch) (!str_cmp(ch->name, "Teophania"))
#define IS_ROLLZ(ch) (!str_cmp(ch->name, "Roll"))
#define IS_REM(ch) (!str_cmp(ch->name, "Rem"))
#define IS_DOMINIC(ch) (!str_cmp(ch->name, "Dominic"))
#define IS_ZERO(ch) (!str_cmp(ch->name, "Zero"))
#define IS_STARWIND(ch) (!str_cmp(ch->name, "Link"))
#define IS_DOMINIC2(ch) (!str_cmp(ch->name, "Domini"))
#define IS_BEAR(ch) (!str_cmp(ch->name, "Fenris"))


/* Special checks for me to do special things only i need to do for testing shit.. */
#define DEVELOPER(ch) !str_cmp(ch->name, "Chili") 
#endif /* _PLAYER_H_ */
